version: '3.8'
services:
  app:
    image: jeffyf/app.js:latest
    ports:
      - "2001:2001"
    depends_on:
      - ollama
    environment:
      - OLLAMA_SERVICE_URL=http://ollama:5000

  ollama:
    image: jeffyf/ollama_llama2:latest
    ports:
      - "11434:11434"
